# Generated by Django 2.2.12 on 2021-09-09 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subexercise',
            fields=[
                ('subexercise_slug', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subexercise_name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('exercise_slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Exercise')),
            ],
        ),
    ]
