# Generated by Django 2.2.12 on 2021-09-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_slug', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=100)),
            ],
        ),
    ]
